import { NgModule } from '@angular/core';
import {
    CalculateGrossPricePipe,
    CatalogueTypePipe,
    ConvertArrayToStringPipe,
    ErrorMessagePipe,
    FilterLogicRelationPipe,
    HasErrorFieldPipe,
    HasFormModePipe,
    HighlightPipe,
    InvoiceGroupNamePipe,
    OrderLogPipe,
    OrderStatusPipe,
    SegmentationViewPipe,
    TaxPipe,
    VisibilityTypePipe,
} from './pipes';

@NgModule({
    declarations: [
        ConvertArrayToStringPipe,
        ErrorMessagePipe,
        FilterLogicRelationPipe,
        HasErrorFieldPipe,
        HasFormModePipe,
        HighlightPipe,
        InvoiceGroupNamePipe,
        SegmentationViewPipe,
        TaxPipe,
        VisibilityTypePipe,
        CalculateGrossPricePipe,
        CatalogueTypePipe,
        OrderStatusPipe,
        OrderLogPipe,
    ],
    exports: [
        ConvertArrayToStringPipe,
        ErrorMessagePipe,
        FilterLogicRelationPipe,
        HasErrorFieldPipe,
        HasFormModePipe,
        HighlightPipe,
        InvoiceGroupNamePipe,
        SegmentationViewPipe,
        TaxPipe,
        VisibilityTypePipe,
        CalculateGrossPricePipe,
        CatalogueTypePipe,
        OrderStatusPipe,
        OrderLogPipe,
    ],
})
export class PipeSharedModule {}
